### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by Motzumoto** [jay3332/obsidian.py#17]
```
CRITICAL:obsidian.node:NODE 'MAIN' | Failed to connect
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Bot.start_obsidian() done, defined at /home/container/utils/data.py:20> exception=ObsidianConnectionFailure("Node 'MAIN' failed to connect (ClientConnectorError): Cannot connect to host 127.0.0.1:3030 ssl:default [Connect call failed ('127.0.0.1', 3030)]")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3030)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/obsidian/websocket.py", line 70, in connect
    ws = await self._session.ws_connect(self.url, headers=self.headers, **self.__internal__)
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:3030 ssl:default [Connect call failed ('127.0.0.1', 3030)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/utils/data.py", line 21, in start_obsidian
    self.obsidian = await obsidian.initiate_node(bot=self)
  File "/home/container/.local/lib/python3.8/site-packages/obsidian/pool.py", line 111, in initiate_node
    await node.connect()
  File "/home/container/.local/lib/python3.8/site-packages/obsidian/node.py", line 230, in connect
    await self.ws.connect()
  File "/home/container/.local/lib/python3.8/site-packages/obsidian/websocket.py", line 79, in connect
    raise ObsidianConnectionFailure(self.__node, exc)
obsidian.errors.ObsidianConnectionFailure: Node 'MAIN' failed to connect (ClientConnectorError): Cannot connect to host 127.0.0.1:3030 ssl:default [Connect call failed ('127.0.0.1', 3030)]
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9e2b8c5310>
```

Any help would be greatly appreciated

**Comment by Motzumoto** [comment]
turns out all we had to do was add a delay so my bot started before it did
